//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArenaGestor.BusinessTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArenaGestor.BusinessTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;concert_list xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;ConcertDto&gt;
        ///    &lt;ConcertId&gt;1&lt;/ConcertId&gt;
        ///    &lt;TourName&gt;Concierto 1&lt;/TourName&gt;
        ///    &lt;Date&gt;2023-09-04T03:00:00&lt;/Date&gt;
        ///    &lt;TicketCount&gt;10&lt;/TicketCount&gt;
        ///    &lt;Price&gt;10&lt;/Price&gt;
        ///    &lt;Protagonists&gt;
        ///      &lt;ConcertProtagonistDto&gt;
        ///        &lt;MusicalProtagonistId&gt;2&lt;/MusicalProtagonistId&gt;
        ///        &lt;Protagonist&gt;
        ///          &lt;MusicalProtagonistId&gt;2&lt;/MusicalProt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExportXML {
            get {
                return ResourceManager.GetString("ExportXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;concert_list xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;ConcertDto&gt;
        ///    &lt;ConcertId&gt;1&lt;/ConcertId&gt;
        ///    &lt;TourName&gt;Concierto 1&lt;/TourName&gt;
        ///    &lt;Date&gt;2023-09-04T03:00:00&lt;/Date&gt;
        ///    &lt;TicketCount&gt;10&lt;/TicketCount&gt;
        ///    &lt;Price&gt;10&lt;/Price&gt;
        ///    &lt;Protagonists&gt;
        ///      &lt;ConcertProtagonistDto&gt;
        ///        &lt;MusicalProtagonistId&gt;2&lt;/MusicalProtagonistId&gt;
        ///        &lt;Protagonist&gt;
        ///          &lt;MusicalProtagonistId&gt;2&lt;/MusicalProt [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImportXML {
            get {
                return ResourceManager.GetString("ImportXML", resourceCulture);
            }
        }
    }
}
