//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArenaGestor.BusinessTest.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArenaGestor.BusinessTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;concert_list xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;ConcertDto&gt;
        ///    &lt;ConcertId&gt;1&lt;/ConcertId&gt;
        ///    &lt;TourName&gt;Concierto 1&lt;/TourName&gt;
        ///    &lt;Date&gt;2023-09-04T03:00:00&lt;/Date&gt;
        ///    &lt;TicketCount&gt;10&lt;/TicketCount&gt;
        ///    &lt;Price&gt;10&lt;/Price&gt;
        ///    &lt;Protagonists&gt;
        ///      &lt;ConcertProtagonistDto&gt;
        ///        &lt;MusicalProtagonistId&gt;2&lt;/MusicalProtagonistId&gt;
        ///        &lt;Protagonist&gt;
        ///          &lt;MusicalProtagonistId&gt;2&lt;/MusicalProt [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string ExportXML {
            get {
                return ResourceManager.GetString("ExportXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;concert_list xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;ConcertDto&gt;
        ///    &lt;ConcertId&gt;1&lt;/ConcertId&gt;
        ///    &lt;TourName&gt;Concierto 1&lt;/TourName&gt;
        ///    &lt;Date&gt;2023-09-04T03:00:00&lt;/Date&gt;
        ///    &lt;TicketCount&gt;10&lt;/TicketCount&gt;
        ///    &lt;Price&gt;10&lt;/Price&gt;
        ///    &lt;Protagonists&gt;
        ///      &lt;ConcertProtagonistDto&gt;
        ///        &lt;MusicalProtagonistId&gt;2&lt;/MusicalProtagonistId&gt;
        ///        &lt;Protagonist&gt;
        ///          &lt;MusicalProtagonistId&gt;2&lt;/MusicalProt [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        internal static string ImportXML {
            get {
                return ResourceManager.GetString("ImportXML", resourceCulture);
            }
        }
    }
}
