# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Build and Test

    env:
      SOLUTION: 'ArenaGestor.sln'
      PATH: './codigo/ArenaGestor'

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      checks: write

    steps:
    - name: Install tar
      run: sudo apt-get update && sudo apt-get install -y tar
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore $PATH/$SOLUTION
    - name: Build
      run: dotnet build --no-restore $PATH/$SOLUTION
    - name: Test API
      run: dotnet test --no-build --verbosity normal $PATH/$SOLUTION